project:
  type: manuscript
  execute-dir: project
  output-dir: docs
  

manuscript:
  article: index.qmd

notebook-links: global

format:
  html:
    comments:
      hypothesis: true
    include-in-header:
    - text: |
        <style>
        .quarto-notebook .cell-container .cell-decorator {
          display: none;
        }
        </style>
  apaquarto-pdf:
    # Can be jou (journal), man (manuscript), stu (student), or doc (document)
    documentmode: man
    keep-tex: true
  docx: default

execute:
  freeze: auto



