project:
  type: manuscript
  execute-dir: project

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    include-in-header:
    - text: |
        <style>
        .quarto-notebook .cell-container .cell-decorator {
          display: none;
        }
        </style>
  tandf-pdf:
    keep-tex: true

execute:
  freeze: true



